### ISSUE TITLE
Running 2.0.2 with Nvidia and AMD cards in rig

### ISSUE THREAD

**Issue by crypcryp** [mining-visualizer/MVis-ethminer#2]
I have a rig that has 4 1070ti's, and 4 AMD Vega 64's. When I ran the miner I had to use --opencl-platform 1 for anything to work, and then only the 1070ti's were recognized and worked. Their operating temps were very low, around 33 degrees C. Since my AMD cards weren't being used, I used the "-di" setting in Claymore to make it only utilize the AMD gpu's so there wouldn't be a conflict, and I started mining Eth with those. When I started to mine with Eth, my 1070's mining 0xbtc went up 40 degrees, into the 70s, though they didn't feel that hot to the touch. The increase was almost immediate.. 2-3 seconds.  It was suggested I post this issue. 

fyi, when I physically unplugged the 1070s from the mobo and started the computer with only the AMD cards, the 0xbtc miner(same one, 2.0.2) worked fine, though the hashrate for the Vega 64's was obviously slow, only around 600. I thought perhaps it was because I had the core clock extremely underclocked to mine Eth, but when I raised the clocks to stock, the hashrate went from 600 mh/s to 500.

**Comment by mining-visualizer** [comment]
Thanks for the report.  My short term goals are to get pool mining working, and then to get a Linux build working.  After that I may tackle issues like this, although I don't have any nVidia cards, so we'll have to solve that problem as well.
