### ISSUE TITLE
Miner hangs after connecting to local geth node

### ISSUE THREAD

**Issue by treevez** [mining-visualizer/MVis-ethminer#3]
I have a fully synced mainnet Geth 1.8.2 node running on localhost.  When I start up the the miner, it gets as far as below and then hangs.

```
d11 20:59:32.690> Connecting to node at 127.0.0.1:8545 ...
d11 20:59:32.783> Connection established.
```

Mining with an infura node works just fine, so I'm hoping for some insight as to whether this is a problem with my Geth setup or a bug in the miner.

**Comment by mining-visualizer** [comment]
Check the log file in `%LocalAppData%/ethminer`  and post the results of one run here.

**Comment by mining-visualizer** [comment]
Also, verify that the node actually is fully synced by typing `eth.syncing` at the geth console.  It should return false.

**Comment by treevez** [comment]
It seems that despite claiming to be done syncing, my geth node was stuck a few blocks behind and had to be resynced.  Apologies for the issue.
