### ISSUE TITLE
bat file example and or ini setting to be changed

### ISSUE THREAD

**Issue by dvdrbls** [mining-visualizer/MVis-ethminer#5]
error! unable to read program settings from .... ini

what am I doing wrong the node settings are not very clear to me

**Comment by mining-visualizer** [comment]
Post the .ini file, except the PK, so I can see what you've got

**Comment by dvdrbls** [comment]
;--------------------------------------------------------
[Node]

; IP and RPC port of your primary node.  Defaults to 127.0.0.1 and 8545
Host=127.0.0.1
;Host=https://mainnet.infura.io/your_api_key
RPCPort=8545

;--------------------------------------------------------
[0xBitcoin]

; Your ETH account and private key.  Note the acct starts with 0x, but
; not the PK.  Mining rewards will be deposited to this account.  Transaction
; fees will be DRAWN from this account.  Make sure you have enough funds!!
; If you have multiple mining rigs, make sure each rig is running under a 
; separate ETH account, to prevent nonce collisions if they happen to submit
; txs at nearly the same time.
MinerAcct=0xD2a596eB2d5A5D728d46EA024D3286b8B54D3731
AcctPK=__________________________________________________

; 0xBitcoin contract address. normally you will not change this.
TokenContract=0xb6ed7644c69416d67b522e20bc294a9a9b405b31

; when your miner finds a solution, transactions will be submitted with this 
; amount of gas (gwei).  You can change this setting 'on the fly' (without having
; to restart the miner).  All other setting changes require the miner to be restarted.
GasPrice=5

; Set to 1 to enable gas price bidding.  Transactions will be submitted
; with [GasPrice] gas, unless there is someone else bidding, in which case
; the gas price will be set to the price of the competing bid + [BidTop], up
; to a maximum of [MaxGasPrice]. This feature has only been tested when running
; Geth as a local node.  It is NOT supported by Infura nodes.
GasPriceBidding=0

; max gas price you're willing to bid up to
MaxGasPrice=35

; the # of gwei to top the highest bidder
BidTop=2

; if you have multiple mining rigs, specify a shared folder to make sure
; multiple miners don't try to submit a solution for the same challenge.
; eg. ChallengeFolder=\\DESKTOP\folder_name
ChallengeFolder=


;--------------------------------------------------------
[ThermalProtection]

; Temperature provider ('amd_adl' or 'speedfan')
TempProvider=amd_adl

; Default temperature at which GPU throttling is activated. This applies to all GPUs on this mining rig.
; Note: throttling is at the hashing level, not the driver level.
ThrottleTemp=80

; Number of seconds after which the entire mining rig will shutdown if one or more GPUs
; remain at or above ThrottleTemp.
ShutDown=20

**Comment by dvdrbls** [comment]
can you help?

**Comment by mining-visualizer** [comment]
Sorry, I somehow lost track of this.  I used the settings you posted in my ini file and the program started fine.  Can you please post the complete program output and error messages, right from startup?  (I'm assuming you get this error at startup?)  Also, post the contents of %localappdata%\ethminer\log.txt

**Comment by dvdrbls** [comment]
Hi, I try with the new minier and couldnt, can you help me? this is the ini file and the bat file 


[General]

;--------------------------------------------------------
[Node]

; If you are pool mining, set the Host and Port to that of your mining pool.
; If you are solo mining, set the Host and Port to that of your node. You can 
; also set these with the -N command line paramater.  The command line overrides
; settings specified here
;
; Examples, POOL MINING:
;    Host=http://your_mining_pool.com   
;    RPCPort=8586
; Examples, SOLO MINING:
;    Host=127.0.0.1
;    Host=https://mainnet.infura.io/your_api_key
;    RPCPort=8545

Host=http://tokenminingpool.com
RPCPort=8586
;--------------------------------------------------------
[0xBitcoin]

; POOL MINING: Your ETH account, to which payouts will be made. THE PRIVATE
;   KEY IS NOT REQUIRED.
; SOLO MINING: Your ETH account and private key.  Note the acct starts with 0x, but
;   not the PK.  Mining rewards will be deposited to this account.  Transaction
;   fees will be DRAWN from this account.  Make sure you have enough funds!!
;   If you have multiple mining rigs, make sure each rig is running under a 
;   separate ETH account, to prevent nonce collisions if they happen to submit
;   txs at nearly the same time. 

MinerAcct=0xD2a596eB2d5A5D728d46EA024D3286b8B54D3731
AcctPK=0000000000000000000000000000000000000000000000000000000000000000


; The remaining settings in this section apply only to SOLO MINING:

; 0xBitcoin contract address. normally you will not change this.
TokenContract=0xb6ed7644c69416d67b522e20bc294a9a9b405b31

; when your miner finds a solution, transactions will be submitted with this 
; amount of gas (gwei).  You can change this setting 'on the fly' (without having
; to restart the miner).  All other setting changes require the miner to be restarted.
GasPrice=5

; Set to 1 to enable gas price bidding.  Transactions will be submitted
; with [GasPrice] gas, unless there is someone else bidding, in which case
; the gas price will be set to the price of the competing bid + [BidTop], up
; to a maximum of [MaxGasPrice]. This feature has only been tested when running
; Geth as a local node.  It is NOT supported by Infura nodes.
GasPriceBidding=0

; max gas price you're willing to bid up to
MaxGasPrice=35

; the # of gwei to top the highest bidder
BidTop=2

; if you have multiple mining rigs, specify a shared folder to make sure
; multiple miners don't try to submit a solution for the same challenge.
; eg. ChallengeFolder=\\DESKTOP\folder_name
ChallengeFolder=


;--------------------------------------------------------
[ThermalProtection]

; Temperature provider ('amd_adl' or 'speedfan')
TempProvider=amd_adl

; Default temperature at which GPU throttling is activated. This applies to all GPUs on this mining rig.
; Note: throttling is at the hashing level, not the driver level.
ThrottleTemp=80

; Number of seconds after which the entire mining rig will shutdown if one or more GPUs
; remain at or above ThrottleTemp.
ShutDown=20

**Comment by dvdrbls** [comment]
tokenminer.exe -P -G
pause

**Comment by mining-visualizer** [comment]
Did you put the `tokenminer.ini` file in `%localappdata%\tokenminer` folder?

**Comment by dvdrbls** [comment]
yep

**Comment by dvdrbls** [comment]
also when i tried to install both the vcredist my system say I already had a newer version and the other one I had it already

**Comment by mining-visualizer** [comment]
I asked you already before to  post the screen output (screen capture would be fine), and post the relevant portion of `%localappdata%\tokenminer\log.txt`  (just the part at the end that your most recent program run).

**Comment by dvdrbls** [comment]
I got it! thank you so much
