### ISSUE TITLE
Getting error message 'Tx failed, gasPrice = x :(' with gas bidding enabled

### ISSUE THREAD

**Issue by treevez** [mining-visualizer/MVis-ethminer#6]
While the miner does not get stuck in a loop bidding against itself anymore, it does seem to not bid at all.  User @jumplove in the discord also claims that bidding was not working for them either.

```
d13 11:01:51.156> Solution found; Submitting to node ...
d13 11:01:51.246> Tx hash :, gasPrice : 15
d13 11:01:52.592> New challenge :
d13 11:02:32.090> Tx failed, gasPrice = 15  :(
```

**Comment by mining-visualizer** [comment]
Gas price bidding does not guarantee that you will always win the bid.  Mostly due to network latency.  Look in the log.txt file for a more detailed info dump of the bidding process.  It shows you who  you were bidding against, if any.  Pay special attention to the times of each event.

If the log doesn't make any sense to you, post the relevant portion here and I'll try to explain it.

**Comment by treevez** [comment]
```
d13 11:01:51.156> Solution found; Submitting to node ...
d13 11:01:51.262> Tx hash :, gasPrice : 15
d13 11:01:52.592> New challenge :
d13 11:01:52.731> Miner submitted tx. gasPrice=15, challenge=
d13 11:02:32.090> Tx failed, gasPrice = 15  :(
d13 11:02:32.090> Miner lost, block:, tx=
d13 11:03:50.771> New challenge :
```

There does not seem to be any bidding that happened.  Several others with a larger count of rejected solutions have reported the same activity as above in discord, that they are losing solutions without any bidding happening.  My latency is under 25ms.  My default gas price is 15.

**Comment by mining-visualizer** [comment]
Ok, here goes.  You submitted a soln on lines 1 & 2, but the node did not receive it until line 4.  It shows that you submited a bid for challenge 4e104923, but just prior to that, a new challenge was issued (line 3), which means your soln was stale.  If you look in the log before the lines you've posted, you will see the miner that submitted for and won challenge 4e104923.

**Comment by treevez** [comment]
Sorry if I did not post enough of the logs.

```
d13 10:51:25.101> New challenge :
d13 10:55:24.293> New challenge :
d13 10:57:27.434> New challenge :
d13 10:58:18.083> New challenge :
d13 10:59:54.176> New challenge :
d13 11:01:10.645> New challenge :
d13 11:01:51.156> Solution found; Submitting to node ...
d13 11:01:51.262> Tx hash :, gasPrice : 15
d13 11:01:52.592> New challenge :
d13 11:01:52.731> Miner submitted tx. gasPrice=15, challenge=
d13 11:02:32.090> Tx failed, gasPrice = 15  :(d13 11:0232.090> Miner lost, block:, tx=
d13 11:03:50.771> New challenge :
d13 11:07:00.196> New challenge :
d13 11:09:40.214> New challenge :
```

I understand the stale solution part, though there is no mention of the miner that submitted for and won challenge 4e104923.  Should there be?

**Comment by mining-visualizer** [comment]
That looks like screen output.  I'm talking about the log.txt output in the %appdata%\ethminer folder.  It has more detailed information.

Also about latency, I was referring to latency in the ethereum network, namely how long it typically takes for blocks or txs to traverse the network.  I did a little experiment during development: I took note of the time my node received each incoming newly mined ETH block and compared it with the timestamp in the block, which would represent when the block was mined somewhere in the world and sent out onto the network.  On average, there was a  7-10 second lag between when the block was  mined and when it reached my node, but on numerous occasions, the lag was up to 30 - 40 seconds. You have to remember, there are about 20,000 nodes in the world.  so you can expect txs to have the same lag.  Somewhere in the world someone might find a soln to the current challenge and submit a tx to a node to be mined in the next ETH block, but your node might not receive that tx for  quite some time.  You might find a soln then also and submit a tx, not even knowing that someone beat you to it.

**Comment by treevez** [comment]
Ah I understand you on latency now.  

And that is in fact the logs from log.txt in LocalAppData.
